version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8081:8081"
    environment:
      - EXPO_PUBLIC_API_URL=http://localhost:8000
      - MAILGUN_API_KEY=example
      - MAILGUN_DOMAIN=example
    volumes:
      - .:/app
    command: >
      sh -c "
      cd /backend && . venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8000 &
      cd /frontend && npm start"