//unused
import { StyleSheet, Dimensions,  } from 'react-native';
const windowWidth = Dimensions.get('window').width
console.log(windowWidth)

export default StyleSheet.create({
    wrapper: {
        height: '100vh',
        overflow: 'scroll',
        backgroundColor: '#121212',
    },
    container: {
        margin: 'auto',
        marginTop: '30px',
        width: '80%',
        height: '100vh',
        paddingBottom: '30px',
    },
    modulecontainer: {
        flexDirection: (windowWidth > 1000) ? 'row' : 'column',
        flexWrap:  'wrap',
        margin: 'auto',
        marginTop: '30px',
        width: '90%',
        paddingBottom: '30px',
        boxShadow: 'rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px',
        //boxShadow: (windowWidth > 1000) ? 'rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px' : 'none', 
     },
     moduletitelcontainer: {
        flexDirection: 'row',
        boxShadow: 'rgba(14, 30, 37, 0.12) 0px 2px 4px 0px, rgba(14, 30, 37, 0.32) 0px 2px 16px 0px',
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 0,
        backgroundColor: '#282828',
        marginLeft: '1%',
        height: '60px',
        width: (windowWidth > 1000) ? '98%' : '100%',
     },
     moduletitel: {
        marginLeft:(windowWidth > 1000) ? '1%' : '5%',
        display: 'flex',
        marginTop: 'auto',
        marginBottom: 'auto',
        color: '#a336c1',
        fontSize: '17px',
        fontWeight: '700',
        flex: 3
     },
     titelicon: {
        flex: (windowWidth > 1000) ? 0.5 : 1,
        display: 'flex',
        marginLeft: 'auto',
        marginTop: 'auto',
        marginBottom: 'auto',
        color: '#a336c1',
     },
     module: {
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 0,
        backgroundColor: '#282828',
        flex: 1,
        marginTop: '30px',
        minWidth: (windowWidth > 1000) ? '32%' : '100%',
        maxWidth: (windowWidth > 1000) ? '32%' : '100%',
        minHeight: (windowWidth > 1000) ? '140px' : '140px',
        maxHeight: (windowWidth > 1000) ? '140px' : '140px',
        marginLeft: '1%',
        boxShadow: 'rgba(14, 30, 37, 0.12) 0px 2px 4px 0px, rgba(14, 30, 37, 0.32) 0px 2px 16px 0px',
        //boxShadow: 'rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px',
    },
    icon: {
        marginTop: '25%',
        color: '#a336c1',
    },
    titel: {
        color: '#a336c1',
        fontSize: '17px',
        marginTop: '12%',
        paddingLeft: '5%',
        fontWeight: '700',
    },
    text: {
        color: 'white',
        fontSize: '16px',
        padding: '5%',
        paddingTop: '1%',
    },
    loadingbar: {
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 0,
        width: '85%',
        marginLeft: '4%',
        marginTop: '20px',
    },
    loadingbargreen: {
        lineHeight: '26px',
        height:'26px',
        width: '100%', 
        backgroundColor:'green',
        textAlign: 'center',
        color: 'white',
        fontSize: '16px',
    },
    loadingbarred: {
        lineHeight: '26px',
        height:'26px',
        width: '100%', 
        backgroundColor:'red',
        textAlign: 'center',
        color: 'white',
        fontSize: '16px',
    },
    loadingbargray: {
        lineHeight: '26px',
        height:'26px',
        width: '100%', 
        backgroundColor:'gray',
        textAlign: 'center',
        color: 'white',
        fontSize: '16px', 
    },
    quizButton: {
        marginTop: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor: '#a336c1',
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    quizButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    
});
